### ISSUE TITLE
想问下，类似于 umi 这种项目，如果进行断点调试呢？

### ISSUE THREAD

**Issue by remotesc2** [xiaohuoni/source-code-co-reading-umi#1]
像这种 nodejs 项目，是否只能使用测试用例这种方式去测试验证吗？

**Comment by dkvirus** [comment]
同问。目前 umi 代码又有些变动，这个工程很有价值，可以一直搞起来呀。
代码里很多 import() 和 require() 混用，我用 vscode 能够打断点，但遇到 import() 就报错误......
@xiaohuoni  大佬能不能写个指南介绍下如何断点调试。

**Comment by xiaohuoni** [comment]
@dkvirus 欢迎PR，断点调试的问题，我直接问一下原作者 https://github.com/sorrycc/ama/issues/23

**Comment by xiaohuoni** [comment]
# 如何断点调试
确保 node 在 8.10 以上，然后执行：
```
$ node --inspect-brk ./node_modules/.bin/umi test
```
然后在浏览器里打开 chrome://inspect/#devices 进行 inspect 和断点。

**Comment by panhuajian** [comment]
@xiaohuoni 试了貌似没用啊，不知道怎么回事一直报错
